export const APP_SCREEN = {
  UN_AUTHORIZE: 'UN_AUTHORIZE',
  LOGIN: 'LOGIN',

  HOME: 'HOME',
  LISTER: 'LISTER',
  GIVER: 'GIVER',
  SETTING: 'SETTING',

  GIFTDETAIL: 'GiftDetail',
  FRIENDGIFT: 'FRIENDGIFT',
  CATALOG: 'CATALOG',
  BRAND_CATALOG: 'BRAND_CATALOG',
  GIVER_SUGGEST: 'GIVER_SUGGEST',
  PRODUCT_DETAILS: 'PRODUCT_DETAILS',
  INVITE_FRIEND: 'INVITE_FRIEND',
};
