export const APP_SCREEN = {
  UN_AUTHORIZE: 'UN_AUTHORIZE',
  LOGIN: 'LOGIN',

  HOME: 'HOME',
  LISTER: 'LISTER',
  GIVER: 'GIVER',
  SETTING: 'SETTING',

  GIFTDETAIL: 'GiftDetail',
  FRIENDGIFT: 'FRIENDGIFT',
  CATALOG: 'CATALOG',
  BRAND_CATALOG: 'BRAND_CATALOG',
  GIVER_SUGGEST: 'GIVER_SUGGEST',
  WEB_VIEW_SCREEN: 'WEB_VIEW_SCREEN',
  PRODUCT_DETAILS: 'PRODUCT_DETAILS',
  PRODUCT_DETAILS_ADD: 'PRODUCT_DETAILS_ADD',
  INVITE_FRIEND: 'INVITE_FRIEND',
  MULTIPLE_FILTER: 'MULTIPLE_FILTER',
  UPDATE_INFOMATION: 'UPDATE_INFOMATION',
  MAP: 'MAP',
  ADD_PRODUCT: 'ADD_PRODUCT',
};
